#!/bin/bash

echo -ne "| Letter | Code |     | Number | Code  | \n"
echo -ne "|========|======|     |========|====== | \n"
echo -ne "| A      | .-   |     | 0      | ----- | \n"
echo -ne "| B      | -... |     | 1      | .---- | \n"
echo -ne "| C      | -.-. |     | 2      | ..--- | \n"
echo -ne "| D      | -..  |     | 3      | ...-- | \n"
echo -ne "| E      | .    |     | 4      | ....- | \n"
echo -ne "| F      | ..-. |     | 5      | ..... | \n"
echo -ne "| G      | --.  |     | 6      | ----. | \n"
echo -ne "| H      | .... |     | 7      | ---.. | \n"
echo -ne "| I      | ..   |     | 8      | --... | \n"
echo -ne "| J      | .--- |     | 9      | -.... | \n"
echo -ne "| K      | -.-  | \n"
echo -ne "| L      | .-.. |     | Symbol | Code   | \n"
echo -ne "| M      | --   |     |========|========| \n"
echo -ne "| N      | -.   |     | .      | .-.-.- | \n"
echo -ne "| O      | ---  |     | ,      | --..-- | \n"
echo -ne "| P      | .--. |     | ?      | ..--.. | \n"
echo -ne "| Q      | --.- |     | /      | -..-.  | \n"
echo -ne "| R      | .-.  | \n"
echo -ne "| S      | ...  | \n"
echo -ne "| T      | -    | \n"
echo -ne "| U      | ..-  | \n"
echo -ne "| V      | ...- | \n"
echo -ne "| W      | .--  | \n"
echo -ne "| X      | -..- | \n"
echo -ne "| Y      | -.-- | \n"
echo -ne "| Z      | --.. | \n"

exit 0
