#!/bin/bash
# Ecco come leggere dei metadati da dei file usando il comando exiftool

if [[ $# < 1 ]]; then
	echo "usage: command [dir]"
    echo "e vedrai che tutti i file annidati nelle sottocartelle di [dir] verranno spostati in [dir]"
	exit 0
fi

if [[ ! -d $1 ]]; then
    echo "fornire una cartella pls"
    exit 1
fi

for file in * 
do
	artist=$(exiftool "$file" | grep "Artist " | cut -d : -f 2 | sed "s/ //")
	album=$(exiftool "$file" | grep "Album " | cut -d : -f 2 | sed "s/ //")
	genre=$(exiftool "$file" | grep "Genre " | cut -d : -f 2 | sed "s/ //")
	
	echo "file: $file"
	echo "artist: $artist"
	echo "album: $album"
	echo "genre: $genre"
	echo "==========================="
done

