#!/bin/bash
# script per convertire il nome di un file
# "Lezione XX - dd.mm.YYYY.md" -> "YYYYmmdd.md"

echo "Questo script è stato creato per un uso molto specifico, convertire i nomi dei file in questo modo:"
echo "Lezione XX - dd.mm.YYYY.md -> YYYYmmdd.md"
echo -n "sei sicuro di voler continuare? [y/n] > "

read answer

if [[ $answer != "y" ]]; then
    echo "ok dai, arrivederci"
    exit 0
fi


if [[ ! -d $1 ]]; then
    echo "pls seleziona (tra i parametri del comado) una cartella valida"
    exit 1 
fi


find "$1" -type f -name "*.md" | while read -r file
do
    estensione=${file##*.}

    giorno=`echo "$file" | cut -d ' ' -f4 | cut -d '.' -f1`

    if [[ $giorno -le 9 ]]; then
        giorno=0$giorno
    fi

    mese=$(echo "$file" | cut -d '-' -f2 | cut -d '.' -f2)
    if (($mese <= 9)); then
        mese=0$mese
    fi

    anno=$(echo "$file" | cut -d '-' -f2 | cut -d '.' -f3)

    nuovo_nome="$anno$mese${giorno}.$estensione"

    #echo "mv "$file" "$1/$nuovo_nome""
    # SCOMMENTA SOLO SE SEI SODDISFATTO DEL RISULTATO ⤵️
    mv "$file" "$1/$nuovo_nome"
done
