#!/bin/bash
# Questo script permette di selezionare una cartella del telefono e sincronizzare il suo contenuto (o solo quello di file che rispettano una espressione regolare) all'interno di una cartella di destinazione (presumibilmente del pc o di un fs montato) fornita in input
# - siccome è stato pensato per sincronizzare la cartella delle foto al momento NON va a considerare ricorsivamente il contenuto della cartella in input
# - la sincronizzazione si occupa solo di controllare se il nome del file è presente o meno (non fa controlli sulla data di modifica)
# - per leggere il contenuto del telefono fa utilizzo di adb

# PRIMA PARTE: CONTROLLO PARAMETRI
# almento 2 parametri
# - source directory (on phone)
# - destination directory (maybe on NAS)
# - regex of the file to consider
if [[ $# -lt 2 ]]; then
    echo "Numero di parametri errato" 
    echo -e "usage: "
    echo -e "    sync_phone_to_pc [path on phone] [path on pc] [regex]\n"
    echo "example: per copiare tutte le foto e immagini scattate nel 2025 sul desktop"
    echo "    sync_phone_to_pc /sdcard/DCIM/Camera ~/Desktop \"2025*\""
    exit 1
fi
# i path forniti non devono avere '/' come carattere finale
lastCharFirstParameter=${1:0-1}
if [[ $lastCharFirstParameter = '/' ]]; then
  echo " a directory must not end with '/' character" 
  exit 1
fi
lastCharSecondParameter=${2:0-1}
if [[ $lastCharSecondParameter = '/' ]]; then
  echo " a directory must not end with '/' character" 
  exit 1
fi
# entrami i parametri devono essere delle directory effettive
if adb shell "test ! -d \"$1\"" < /dev/null; then
    echo "$1 non è una directory" 
    exit 1
fi
if [[ ! -d "$2" ]]; then
    echo "$2 non è una directory" 
    exit 1
fi
# se il parametro regex non è stato fornito viene importato a *
regex='*'
if [[ $3 != "" ]]; then
    regex=${3}
fi


# SECONDA PARTE: COPIA EFFETTIVA DEI FILE MANCANTI
# ciclando sui file del telefono per ogni file controllo la sua esistenza nella directory di destinazione
# se il file non è presente viene fatto un pull altrimenti skip
fileTotali=$(adb shell "find \"$1\" -type f -name '$regex' | wc -l")
i=1
adb shell "find \"$1\" -type f -name '$regex' -exec basename {} \\;" | while read -r file; do
    echo "$i/$fileTotali"  
    if [[ -f "$2/$file" ]]; then
        echo "file già presente: $file"
    else
        echo "trovato file mancante: $file"
        adb pull "$1/$file" "$2" < /dev/null
    fi
    i=$((i + 1))
done
